### ISSUE TITLE
Purpose of Repository

### ISSUE THREAD

**Issue by chgibb** [v8/node-fast-ffi#1]
I was intrigued by the repository name and so immediately clicked, hoping for some resolution to Node's notoriously bad FFI. However, it appears this repo is empty and unused.   What is its purpose?

**Comment by ofrobots** [comment]
Hi @chgibb. Thanks for your interst. We are prototyping a VM-supported FFI. We are not too far along yet, so nothing exists in this repo at this point. We will populate this once we have something concrete.

**Comment by chgibb** [comment]
@ofrobots thanks!
